module NeuronDDS
{
	const long	MAX_NAMELEN = 32;
	typedef string<MAX_NAMELEN>		Name;
	typedef sequence<octet>			Buffer;		
	
	struct SrcAdvert
	{
		long	srcID;  //@key
		Name	srcName;
	};
#pragma keylist SrcAdvert srcID
	
	struct Frame
	{
		long	srcID;  //@key
		long	index;
		long	layerType;
		long	size;
		Buffer	payload;
	};
#pragma keylist Frame srcID

	struct ThrotMsg
	{
		long srcID;  //@key
		long mode;
	};
#pragma keylist ThrotMsg srcID
};

